### ISSUE TITLE
wordpress Query string not exist redirect to 404 for sam page url.

### ISSUE THREAD

**Issue by dharmeshtops** [stevegrunwell/wp404#8]
I have URL: http://localhost/tenerifenew/property-view/OUT01091/

above URL is custom developed. I want 404 if query string "OUT01091" is not found with my conditional logic.
Wordpress by default showing 404 page if page not found is different from my this custom URL so it is not working with the custom so how to solve it.

**Comment by stevegrunwell** [comment]
WP404 ties into the WordPress 404 handling, so it won't be able to log errors for URLs that aren't routed through WordPress.

If you want insight into the 404 responses served by Apache directly, you'll need to refer to the `access.log` file for your web server. There are some [helpful command line tricks](http://www.commandlinefu.com/commands/view/9117/extract-all-404-errors-from-your-apache-accesslog-prefix-lines-by-occurrences-number) to help you filter the list down to only show 404 errors.
